### ISSUE TITLE
Дефибы всё ещё не проверяют наличие призрака в теле!

### ISSUE THREAD

**Issue by MorJams** [frosty-dev/ss14-feedback#1]
**Описание ошибки**
При использовании дефиба на трупе в котором нет призрака он выдаёт ошибку, говоря что реанимировать в таком случае невозможно, но всё равно воскрешает труп. При этом если гост не в теле - он может гулять призраком даже когда его тело оживили и вернуться в тело когда хочет, что может создать проблемы когда человек за гостоту палит роли и возвращается после этого в любое удобное ему время.

**Для воспроизведения ошибки**
Использовать дефиб на труп, в котором нет госта.

**Ожидаемое поведение**
Труп не должен реанимироваться без госта.

**Скриншоты/логи**
![2023-06-30 18-58](https://github.com/frosty-dev/ss14-feedback/assets/8451186/4f4382be-d1e2-4e6c-bfb3-c6736a66e9b2)

**Дополнительная информация**
Дефиб УЖЕ выдаёт ошибку и говорит, что тело воскресить невозможно пока призрак не вернётся. Осталось это только реализовать. На классической станции медики просто по несколько раз дефиб используют, намекая призраку на то, что надо в тело вернуться. И использование дефибом более одного раза как-то даже атмосфернее, штоле... _Из-за этого бага невозможно нормально умереть, блин!_

Добавил скриншот, который прямо говорит, что надо пытаться ещё и ещё, при этом во время этого сообщения если что тело УЖЕ воскресили.

**Comment by Aviu00** [comment]
Фича?

**Comment by MorJams** [comment]
> Фича?

Нет, не фича. Внимательно посмотри на сообщение на скриншоте. "Попытка реанимации не удалась" когда при этом она УДАЛАСЬ - немного странное сообщение для фичи.
