### ISSUE TITLE
[Feature] Убрать уведомления от приложения

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#10]
Убрать получение "уведомления" от приложения сс14 во всех случаях. Я вижу с всплывающей панелью задач, и я ебал рот, когда она всплывает по всякой хуйне.

СС14 автоматически срет, когда в ахелп приходит сообщение, происходит рандомивент или оповещение от капитана.

![image](https://github.com/frosty-dev/ss14-feedback/assets/88589686/35b33718-a81f-4ad0-a635-9ed2d3184340)

**Comment by rhailrake** [comment]
no
