### ISSUE TITLE
Борга можно дизармнуть

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#100]
Боргу можно дизармнуть его инструмент, который находится в активной руке.

**Comment by N1ght-Raven** [comment]
Если я правильно понял что значит дизармнуть то у меня была такая хуйня, вот скирин как у меня пропал лом
![White Dream 14 11 09 2023 11_45_57](https://github.com/frosty-dev/ss14-feedback/assets/92939058/2b883eea-b4ee-46d2-b2b2-c6c65de00e26)

**Comment by Cinkafox** [comment]
Исправлено.
