### ISSUE TITLE
Музыка.....

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#105]
В лобби вернули не всю музыку, только лишь ее часть. Я могу понять, что у спейс эсхол там права авторские, все дела, по крайней мере мне так сказали. Но с другой музыкой которую не вернули же нет таких проблем? 
Прошу вернуть... мы все скучаем.
Было бы неплохо ещё и добавить другую подобную этим трекам музыку, но это уже так, мечты..

**Comment by RavMorgan** [comment]
Не.
