### ISSUE TITLE
[Feature] АдминоАнсиин

### ISSUE THREAD

**Issue by SimobiSirOP** [frosty-dev/ss14-feedback#106]
- Описание идеи: Новый элемент, вещество, химикат. Админоансиин(Имя под вопросом)
- Прыская им на тайлы, Все, кто с кнопками не видят что на этих тайлах(В том числе, ПКМ и другие способы)(Будет просто темнота)
Прочистить можно только используя Кнопки Коммандера, и новую команду /removeunseen
На каждом тайле нужно минимум 0.125 Админоансиина. (1u= 8тайл)
Полезно для скрытных самоантагов

Админоансиин(1u)(Рецепт обсуждаем)

 - Норэпинефриновая кислота(5u)
 - Омнизин(5u)
 - Бананиум(5u)

- Возможная реализация: Код темноты?

- Дополнительные детали: Будет потом

- Деньги: Возможно

**Comment by RavMorgan** [comment]
Нет

**Comment by SimobiSirOP** [comment]
Тогда я сам сделаю!
