### ISSUE TITLE
СБшники стартуют с магазином для пистолета, но без пистолета

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#11]
Офицеры, кадеты, Хосы и вардены стартуют с летальным магазином в рюкзаке, но без самого пистолета.

![image](https://github.com/frosty-dev/ss14-feedback/assets/88589686/d87fbdd1-9bb3-4e69-815d-25bd8337b2c9)

**Comment by rhailrake** [comment]
Fixed.
