### ISSUE TITLE
Химический раздатчик и ХимМастер работают без электричества.

### ISSUE THREAD

**Issue by DeusExInfinity** [frosty-dev/ss14-feedback#115]
**Описание ошибки**
Если открутить от пола гаечным ключом и открутить панель установки, то она будет работать без электричества, и даже без присоединения к полу. Весь интерфейс установки продолжает быть доступен и выдаёт все необходимые реагенты.
**Для воспроизведения ошибки**
Шаги для воспроизведения проблемы:
1. Открутите отвёрткой панель Раздатчика Реагентов
2. Открутите его от пола гаечным ключом
3. Вы можете им пользоваться, даже в открытом космосе.

**Ожидаемое поведение**
Оно должно не работать в таких условиях.

**Скриншоты/логи**
![image](https://github.com/frosty-dev/ss14-feedback/assets/148000360/1ccd8c2d-4908-4c3f-8cd5-bde58c48c540)
![image](https://github.com/frosty-dev/ss14-feedback/assets/148000360/55bf1612-9fb8-47f5-a077-065ee498d948)
![image](https://github.com/frosty-dev/ss14-feedback/assets/148000360/60fb0da8-72d8-407c-b81d-798abfd679c8)

**Дополнительная информация**
Мне сообщили, что злобные багоюзеры-рецидевисты используют этот баг более полугода. Я хочу предотвратить этот порочный круг нарушений опубликовав этот баг-репорт.

**Comment by Sevasstyan** [comment]
Сука, это фича блять, не смей посягать на святое.

**Comment by DeusExInfinity** [comment]
> Сука, это фича блять, не смей посягать на святое.

НЕЕЕЕЕЕЕЕЕЕЕЕЕТ. Так не должно быть!
