### ISSUE TITLE
Мëртвый щит?

### ISSUE THREAD

**Issue by Tryalkash** [frosty-dev/ss14-feedback#116]
При выстреле в мëртвое тело, которое носит скафандр, тело просто впитывает в себя в пулю, чего быть не должно.

Как воспроизвести этот баг?
1. Убить человека в скафандре
2. Пошмалять в него
3. Увидеть что пули впитываются

Как это должно работать?
Пуля должна пролететь над телом.

Чаще всего у меня баг происходил с Христовым.

**Comment by Sevasstyan** [comment]
Ты уверен в этом? Может дело именно в христове? Просто у меня такого не было никогда за последнее время, и я даже четко помню что стрелял через тела в скафах.
Тебе нужно было бы еще и логи скинуть, но уже поздно.
