### ISSUE TITLE
Копье не работает.

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#129]
Если сделать простое копье, намазать скажем аматоксином, и кинуть, то в человека введется 0 ядов. Хотя должны все 5 унций. Проверил остальные копья тоже не вводят реагент при броске.
Также все копья кроме обычного не метаются нормально, а как обычный предмет.

**Comment by Aviu00** [comment]
Оно и не должно вводить реагенты. Это в апстриме только есть.

**Comment by Sevasstyan** [comment]
> Оно и не должно вводить реагенты. Это в апстриме только есть.

Ох... понял, немного забежал вперед
