### ISSUE TITLE
Бессмертие!

### ISSUE THREAD

**Issue by Tryalkash** [frosty-dev/ss14-feedback#148]
Энергетический щит делает тебя бессмертным

Как же получить бессмертие?
1. Купить энергощит
2. Вырубить его
3. Поднять щит
4. Теперь вы неуязвимы к основным типам урона (кроме радиации, аирлосса, ядам и стан урона)

Как это должно работать?
Как обычный щит, тоесть НЕ ЗАБИРАТЬ 100% УРОНА.

**Comment by Aviu00** [comment]
Пофикшено
