### ISSUE TITLE
[Feature] Добавить в культочат имена

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#17]
## Реальные имена

Можно добавить в культочат реальные имена персонажей, как в обычных рациях.

## Засекреченные имена

Или проименовать людей как Мистер/Миссис ГреческаяБуква, к примеру Мистер Альфа, Миссис Пси и т.п. 
Как генокрады в чате генокрадов сс13.

![image](https://github.com/frosty-dev/ss14-feedback/assets/88589686/1c324705-10c0-430c-b588-709c61edb12e)

**Comment by Aviu00** [comment]
Пофикшено.
