### ISSUE TITLE
Отсутствие раундстарт боргов [GRID/WhiteBox]

### ISSUE THREAD

**Issue by iDesmond** [frosty-dev/ss14-feedback#19]
**Описание ошибки**
На сервере Грида отсутствуют на карте раундсартом борги, в то время как на мэйде они присутствуют, на то же самой карте. 

**Для воспроизведения ошибки**
Все раунды

**Скриншоты/логи**
![image](https://github.com/frosty-dev/ss14-feedback/assets/44869755/16614609-e641-4e0a-ad0f-b1d68e4c14e1)

**Дополнительная информация**
Проблему заметил ещё с выхода боргов, не знаю почему все игнорируют и не верят мне

**Comment by rhailrake** [comment]
Есть.
