### ISSUE TITLE
[Feature] Генераторы слишком бесконечные, нужен баланс

### ISSUE THREAD

**Issue by SimobiSirOP** [frosty-dev/ss14-feedback#20]
- Описание идеи: Сделать генераторы зависимыми от ресурсов. На данный момент плазменные/урановые генераторы являются бесконечными, и даже не используют данные ресурсы в крафте. По данной причине, нужно добавить необходимость загружать уран/плазму в генераторы для работы.

- Возможная реализация: Стыбзить код с ядерки, или использовать уже имеющийся компонент(если он есть)

- Дополнительные детали: I didn't got any sprites.

- Деньги: я скинул 10 рублей на бусти godblessedoleg, обанкротив его на 20 рублей, так что уже оплачено на -20 рублей.

**Comment by Semk5** [comment]
Ты меня заставил зарегаться на гитхабе, за что спасибо, но всё таки блять покайся, эту _фичу_ нормально просто не воспринять, теперь или дам на шатттле делать, чтоб его пропитать, или кучу плазменных генераторов, что не меньше места жрет. Так к чему это всё...
### Это говно какое то, не нравится буквально никому, когда откатите?

**Comment by SimobiSirOP** [comment]
> Ты меня заставил зарегаться на гитхабе, за что спасибо, но всё таки блять покайся, эту _фичу_ нормально просто не воспринять, теперь или дам на шатттле делать, чтоб его пропитать, или кучу плазменных генераторов, что не меньше места жрет. Так к чему это всё...
> 
> ### Это говно какое то, не нравится буквально никому, когда откатите?

ЭТО ЛУ

**Comment by SimobiSirOP** [comment]
Блять случайно закрыл

**Comment by SimobiSirOP** [comment]
> Ты меня заставил зарегаться на гитхабе, за что спасибо, но всё таки блять покайся, эту _фичу_ нормально просто не воспринять, теперь или дам на шатттле делать, чтоб его пропитать, или кучу плазменных генераторов, что не меньше места жрет. Так к чему это всё...
> 
> ### Это говно какое то, не нравится буквально никому, когда откатите?

ЭТО ЛУЧШАЯ ФИЧА. На данный момент все питание - Поставь генератор, тебе достаточно. С ограниченным топливом генератора, станет круче. Если эта фича не зайдёт здесь, напишу пендосам

**Comment by Aviu00** [comment]
В апстриме уже это добавили https://github.com/space-wizards/space-station-14/pull/18387
