### ISSUE TITLE
Борги и дефибриллятор

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#22]
Борга можно воскресить дефибриллятором, если предварительно починить.

**Comment by rhailrake** [comment]
@Cinkafox

**Comment by Cinkafox** [comment]
И так, насчёт дефибрилляторов. Можно конечно сделать так, чтобы дефибриллятор не сработал на борга, но это создаст кучу хардкода, потому что система дефибриллятора захардкожен к хренам.. Да и если подумать, это логично. Мы даём боргу заряд для запуска.

**Comment by iDesmond** [comment]
скорее уж тогда не заряд, потому что в них остаётся заряд, а искру зажигания, ну тогда у нас борги работают на ДВС

**Comment by Pantera5641** [comment]
Это баг? Я думал фича
