### ISSUE TITLE
Культ

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#26]
Является ли багом то, что нимбы над головами культистов появляются при достижении общего количества культистов в 8-10 человек, при населении станции в 100-110 человек? Или это сделано намеренно? Вроде бы нимбы должны появляться когда культистов 40% от населения станции, а не 10. 
Имеет ли смысл сделать так, чтобы когда количество живых культистов падало меньше порогового значения, то нимбы у всех исчезали?

Боргам абсолютно все равно на барьеры и шлюзы культа. Я думаю так быть не должно, они хотя бы не должны иметь возможность открывать шлюзы культа. 

Осколки душ от конструкта ремесленника не являются гост ролью. Надо бы добавить, а то он вообще бесполезный какой-то, ну или убрать скилл вообще, чтобы лишний раз не обнадеживать... Также он вроде как должен разрушать стены всего парой ударов, в игре у него но стенам ноль урона.

Точильный камень нихуя не точит.

Если игрок на осколке души, который поместили в оболочку, закроет меню выбора конструкта, он уже не сможет больше выбрать кем стать, и будет просто вечно лежать. Ну или они просто гипер тупые и не могли нажать на себя еще раз в раундах, в которых я играл, не уверен на100%, но решил написать. Почему это меню выбора вообще можно закрыть, может стоит сделать его не закрываемым и сойдет? 

Иногда нужно нажать по три или четыре раза при создании предмета на кузнице, архивах, алтарях, прежде чем оно соизволит его скрафтить. То же самое с руной взятия заклинаний. Наверное это связанно с пингом или типо того.

Почему нету окон в культистком стиле, таких как стены и пол со шлюзом? :< 

Почему спрайты конструктов выглядят так... сильно выбивающееся среди общей стилистики культа? Когда все имеет темные, красные, коричнево-болотные цвета, конструкты черно-белые. Если ремесленник и фантом еще хотя бы выглядят нормально, то джаггернаут прям очень странный.. Почему не были использованы классические спрайты? Странно что жнецы выглядят по классике.  

Немножно насрал. 
Спасибо за культ, супер пиздатый режим. Надеюсь в будущем будет полностью доработан.

**Comment by Remuchi** [comment]
АААААА 
1. Намерено, фича. По поводу убирания подумаю. Вроде и так должно работать!
2. Запретим боргам открывать шлюзы культа. Займусь потом
3. Уже сделала, сколько зальем.
4. Посмотрим. Надо поспрашивать будет Лида по поводу баланса.
5. Пока не могу узнать, в чем проблема. Постараюсь разобраться! На локалке мне не удалось отследить похожую проблему с руной телепорта. 
6. Я не художник c;
7. Я не художник c;
