### ISSUE TITLE
Говеный спрайт жажды

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#28]
У жажды апстримнулся говеный спрайт, старый был лучше.

![image](https://github.com/frosty-dev/ss14-feedback/assets/88589686/06d312bc-8964-4e8b-a5d3-bc19b5c9e6c5)

**Comment by Aviu00** [comment]
Как по мне, новые спрайты голода и жажды получше выглядят, они к тому же анимированные и "Colourblind-friendly". Я бы новые оставил.

**Comment by ThereDrD0** [comment]
> Как по мне, новые спрайты голода и жажды получше выглядят, они к тому же анимированные и "Colourblind-friendly". Я бы новые оставил.

Мне не нравится их синяя обводка, даже у еды.

**Comment by Sevasstyan** [comment]
Лично я уже привык. Считаю лучше оставить, выглядят приемлемо
