### ISSUE TITLE
[Feature] Запрет /суициде в скованном виде

### ISSUE THREAD

**Issue by fluxer0** [frosty-dev/ss14-feedback#3]
- Описание идеи: Запретить суицид в наручниках. Четко, и понятно э.

- Возможная реализация: Ну откуда я знаю, я что, программист?

- Дополнительные детали: -locksuicide if in handcuffs;

- Деньги: Бюджет Белая Мечта

**Comment by ImHappyRomans** [comment]
А зачем это запрещать? Ну это же реалистично, преступнику есть, что скрывать и чтоб его не раскололи, как орешек он откусывает себе язык. Или я не прав?

**Comment by RavMorgan** [comment]
Зачем?
