### ISSUE TITLE
Трейсеры от пуль 

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#34]
Трейсеры от пуль летают в космосе вместе со станцией, На картинке нагляднее, выстрелы были в эту же стену.

![image](https://github.com/frosty-dev/ss14-feedback/assets/88589686/b4f4943c-e54e-46e3-a444-54cd5bc27152)

**Comment by Sevasstyan** [comment]
А когда начинают стрелять на эвакуационном шаттле вообще пиздец, трейлы летят хуй пойми куда, как и лазеры, а если точнее то летят они вниз, так как шаттл летит вперед. Выглядит очень странно.
