### ISSUE TITLE
[Feature] Более быстрый СЛР

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#37]
СЛР сейчас невероятно медленный и замедлить смерть он может разве что на секунд 5, а стабилизировать и подавно нет.

Предлагаю ускорить темпы проведения СЛР, потому что ну ебанный рот, он пиздец какой юзлесс.

**Comment by Sevasstyan** [comment]
Полностью поддерживаю, имеет смысл только если несколько людей делают слр одному человеку, тогда он более менее поддерживает жизнь. 
(Ну да, одному человеку слр могут делать сразу несколько людей..., но я представляю это как если бы в реале каждый  по очереди вдыхал ему воздух в легкие, хз)
