### ISSUE TITLE
В культ поиграть невозможно.

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#40]
ИЗМЕНИТЕ ШАНС ПОЯВЛЕНИЯ РЕЖИМА "КУЛЬТ" ПОЖАЛУЙТСА!
Я и целая куча людей из лобби, и моих знакомых, ждали культ целый день, с часу дня до часу ночи, и ни разу блять не было культа. ДАЖЕ ЕБУЧИХ ЗОМБИ было уже три раза, какой пиздец... 
Вчера тоже ждал весь день почти, был культ только один раз, и то я не стал культистом, и их в конце концов просто прилетело и уебало ОБР нахуй.
Пять процентов на шанс (как мне ответили) это просто пиздец какой-то, раз в год буквально культ прокает, а это литерали режим ради которого только стоит играть в сс14, как мы жили без него, хуй его знает! 
Триторы ебаные ну просто уже доебали ей богу, обычная смена, только кто-то кого-то периодически убивает в техах, и все нахуй.
Сколько можно ждать этот культ... ну сколько можно... 

А люди которые любят обычную работку с триторами, просто идите нахуй, успеете поработать свою работу, культ в любом случае прям сильно часто не будет прокать. НО НУЖНО СДЕЛАТЬ ЧТОБЫ ХОТЯ БЫ В ТЕОРИИ МОЖНО БЫЛО ПОИГРАТЬ ОДИН РАЗ В КУЛЬТ ЗА ДЕНЬ, А НЕ СИДЕТЬ 9 ЧАСОВ ПРОСТО ЧТОБЫ ЗАЙТИ, ПОБЕГАТЬ, УЗНАТЬ ЧТО НИ ТЕБЕ КУЛЬТ НЕ ВЫПАЛ, НИ ВООБЩЕ НИКОМУ, И ВЫЙТИ НАХУЙ ДО НЕКСТ РАУНДА, И ТАК РАЗ ЗА РАЗОМ В НАДЕЖДЕ НА ИЗМЕНЕНИЕ.

(Мне теперь интересно какой шанс у нюки, если зомби чаще прокают блять, это где видано нахуй?)

**Comment by rhailrake** [comment]
сколько процентов предложишь тогда?

**Comment by Sevasstyan** [comment]
Можешь пожалуйста назвать проценты каждого режима? Чтобы я мог прикинуть примерно, как часто будут выпадать разные режимы и предложить свой вариант

**Comment by Sevasstyan** [comment]
Ну если без общих цифр, то хотя бы 15%, или да 20%. Раунды с культом обычно быстрые, либо все срочники и быстро сливаются, либо все опытные и быстро кончают, так что даже если будет выпадать частенько, успеют хомячки потом поиграть час или два в свою работку после культа.

**Comment by Sevasstyan** [comment]
Я просто не понимаю, а зачем его вообще тогда полгода делали? Чтобы сделать шанс в 5%, и ну, в него играли раз в день в лучшем случае? Были дни уже, когда культа не было ни разу за весь день, с часу дня до часу ночи. И так часто будет, с таким шансом то.

Как люди учиться вообще будут? Если культ блять и прокает, то там максимум один что-то занает, и то не факт. Остальные вообще ноль. И так будет ну, всегда? С таким шансом то. И в чем тогда смысл? Когда культ наконец-то прокнет, он будет пиздец тухлым. Как было сегодня. 

Я культистом не стал, другие стали. Очень долго играли раунд и даже не знали что культ есть. В итоге потом нашли пару рун и металл рунный, убили пару культистов, и доиграли раунд как обычный, даже без триторов, просто был какой-то один культист, который не палился, или не знал блять кто он, просто пиздец.

**Comment by Sevasstyan** [comment]
> сколько процентов предложишь тогда?

Ну если говорить без процентов шанса всех режимов, чтобы оценить более здраво, то я предлагаю хотя бы 15%, или даже 20%. Раунды с культом обычно быстрые, либо все срочники и быстро сливаются, либо все более мене опытные, или хотя бы несколько, и быстро кончают, так что даже если будет выпадать частенько, успеют хомячки потом поиграть
 час или два в свою работку после культа.

**Comment by Sevasstyan** [comment]
Я просто не понимаю, а зачем его вообще тогда полгода делали? Чтобы сделать шанс в 5%, и ну..., в него играли раз в день в лучшем случае? Были дни уже, когда культа не было ни разу за весь день, с часу дня до часу ночи. И так часто будет, с таким шансом то.

Как люди учиться вообще будут? Если культ блять и прокает, то там максимум один что-то занает, и то не факт. Остальные вообще ноль. И так будет ну, всегда? С таким шансом то. И в чем тогда смысл? Когда культ наконец-то прокнет, он будет пиздец тухлым. Как было сегодня.

Я культистом не стал, другие стали. Очень долго играли раунд и даже не знали что культ есть. В итоге потом нашли пару рун и металл рунный, убили пару культистов, и доиграли раунд как обычный, даже без триторов, просто был какой-то один культист, который типо "не палился", или не знал блять кто он, и что ему нужно делать, просто пиздец.

**Comment by Sevasstyan** [comment]
Только что был культ на мейде, какое же позорище.

Я зашел когда раунд длился уже 30 минут. Пробежался везде в техах за инструментами, культ не увидел. 
Потом я занимался работкой, и через 5 минут случайно увидел зачатки культа, пару людей собрались под рнд с кинжалами и зачем-то делали разгерм... Потом они обосновались в рнд снизу (мапа бокс). То есть только спустя 30 минут они что-то начали делать.
Ну, поставили там все культисткие штуки, нимбов до сих пор у них не было, то есть их было меньше 8-10. Потом я пошел в мед набрать лекарств. Пришел обратно, а их всех просто перестреляли нахуй пока я туда бежал, и все, конец раунда.
Один из самых тухлых раундов.

И так будет, ну, всегда? Есть очень много из тех, кто заходит поиграть и не сидят при этом в дискорде или на вики, то есть о культе не знают абсолютно ничего. И учится будут только в самой игре. 
А как они будут учится, если за все три дня, культ на всех основных серверах был только 5 раз максимум?

Я слышал что много метагеев во время культа, которых нужно пиздить и всем объяснять. И типо из-за этого культ такой редкий...  А как то, что культ редкий, поможет в борьбе с метой? Тут же только обратный эффект будет. Если культ будет раз в пол года, люди от этого умнее не станут. 

Если культ будет чаще, то куда больше людей, которым дали пизды за мету, поймут что так нельзя. Ну и люди лучше будут играть в культ, так как будет время на тренировку. 
Конечно я понимаю что педалям сложно объяснять миллиону человек как и что. Я могу предложить написать целый шаблон, который бы пояснил все за мету, и как нужно себя вести. Потом кидать это в ахелп, и через пару минут банить.

Делали такой охуенный режим, чтобы в него не играть. Это просто чудо, если челик хотел в культ, и вдруг хоба, ему в этот же день и культ выпал и роль культиста, реально блять чудо.

**Comment by Aviu00** [comment]
Поставлю 15%
