### ISSUE TITLE
Слезоточивая граната

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#44]
Слезоточивая граната моментально ослепляет персонажа, при чем надолго. Достаточно просто войти и выйти в дым, чтобы ослепнуть на достаточный период времени.

Хотя сама граната в сс13 сначала мылила персонажу глаза на протяжении около 10 секунд нахождения в дыму, нанося дамаг глазам. А после уже ослепляла.

Ей стоит понерфить ослепляющий эффект и добавить замыливание экрана для коротко временного нахождения в дыму.

**Comment by Sevasstyan** [comment]
Да, если достаточно долго постоять в дыму, можно потерять зрение на минут 5 где-то, если не больше. Работает очень странно.

**Comment by Sevasstyan** [comment]
ПОЖАЛУЙСТА ПОФИКСИТЕ ЭТО, ИЛИ ПУСТЬ ОКУЛИН ВЫЛЕЧИВАЕТ ЭТУ ХУЙНЮ. Это просто пиздец ебаный. Можно по 5 минут сидеть и ждать как долбоеб пока начнешь видеть. А все может быть из-за какого-то рандомного хуесоса, который кинул дымовую гранату под ноги в коробке. КОТОРАЯ ДАЖЕ НЕ ПИКАЕТ. То есть ну реально ПИЗДЕЦ.

**Comment by Aviu00** [comment]
Ок пофикшу
