### ISSUE TITLE
Труп не встаёт

### ISSUE THREAD

**Issue by DaniilMak** [frosty-dev/ss14-feedback#50]
**Описание ошибки**
Имеем: Труп, общего урона меньше чем 200, душа есть, надписи о гниении нет.
После использования дефибрилятора НИЧЕГО не меняется, как будто тело уже гниёт, и его не спасти.

**Для воспроизведения ошибки**
Иногда появляется, иногда отсутствует, так что не знаю можно ли её повторить на локальном сервере

**Ожидаемое поведение**
Тело должно было перейти в критическое состояние и начать задыхаться

**Скриншоты/логи**

**Дополнительная информация**
Этот баг появился 3 дня назад примерно и встречался мне 5 раз, только недавно понял что об ошибках надо писать сюда.
От себя могу добавить, что возможно таймеры гниения были изменены, а таймеры появления надписи при осмотре Shift-кликом не были

**Comment by Aviu00** [comment]
Фича, если в теле нет души, то оно не воскреснет.
https://github.com/frosty-dev/ss14-feedback/issues/1

**Comment by DaniilMak** [comment]
Понял, спасибо
