### ISSUE TITLE
Необъяснимые нонреги с жуткого клинка (меч который крафтят культисты на кузнице).

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#52]
Сталкиваюсь с этим каждый раз, как становлюсь культистом. 

Крафчу жуткий клинок на кузнице и повязку зелота. 
Иду пиздить мирный люд для обращения в лучшую религию мира. 

И вот, обычно на втором или третьем ударе, я бью, урон проходит (вижу по медхуду, который дает повязка), чел падает, и спустя пол секунды или меньше, он встает обратно, и урон тупо откатывается. 
Такое у меня иногда происходило вплоть до 3-5 ударов подряд...

С любым другим оружием у меня абсолютно никаких проблем нету, все удары регает. 
А с жутким клинком буквально каждый раз не регает 1-2 удара по цели, и почему-то обычно не регает в тот самый момент, когда цели остался один удар до крита. Бью размахом с ПКМ. 
И нет, дело не в промахах, потому что удар четко происходит, но потом просто откатывается все назад.

Спросил еще у троих человек, они согласились, у них точно такая же проблема. 

Вот логи, если они помогут.

[client.stdout.log](https://github.com/frosty-dev/ss14-feedback/files/12328394/client.stdout.log)

Ред: Эта хрень все еще продолжается. В недавней смене опять тоже самое. Но теперь урон будто блять режется. Сначала чел падает, здоровья уходит дохуя. Потом он  сразу встает и где-то половина здоровья возвращается обратно. Я вообще не понимаю что за херня. С другим оружием по прежнему нету никаких проблем.

Вот вторые логи.

[client.stdout.log](https://github.com/frosty-dev/ss14-feedback/files/12361476/client.stdout.log)

**Comment by Aviu00** [comment]
Проблема настроек сети.
