### ISSUE TITLE
Зеркальный щит станит культистов 

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#59]
Не секрет что если кинуть зеркальный щит в человека, то он застанится, а щит вернется в руки к владельцу. 

Однако, если кинуть щит не в обычного человека, а в культиста, будучи самим культистом, то он застанится.

Мне кажется это скорее жирный баг, чем фича. Причем ты можешь буквально застанится об свой же щит. Если кинешь его слишком близко к своим ногам, или об стену которая впритык. Это пиздец.

**Comment by ThereDrD0** [comment]
Звучит как фича, учись робаститься!

**Comment by Sevasstyan** [comment]
> Звучит как фича, учись робаститься!

Возможно ты и прав. Но то, что меня свои же культисты по сути убивают, когда в узких коридорах пытаются попасть во врагов, а в итоге станят меня и я умираю, как-то не очень. Мне теперь как в доте, играть и против врагов, и думать как бы мне свои же союзники не поднасрали? 
Хуевая фича какая-то. Тем более что оружие культистов в принципе не должно наносить урон другим культистам, как в сс13. 
Ну, в принципе с другой стороны, стан таким дешевым способом это довольно сильно, возможно эта фича будет некой ценой за такую силу, как бы маленькая чайная ложка дёгтя в бочке с медом. Но хрен знает если честно, я скорее против.
