### ISSUE TITLE
Много о культе

### ISSUE THREAD

**Issue by GGLOVV** [frosty-dev/ss14-feedback#6]
1.)
1Вызов Насри не заканчивает раунд

2.Вызвать Насри

3. Окончание раунда после вызова насри с победой культа

4. 
![image](https://github.com/frosty-dev/ss14-feedback/assets/140979503/7d5a60fa-dec1-4f90-ae29-ad36e8dffe8f)

**Дополнительная информация**
5 знаю что у вас уже была об этом инфа от педаль состава уж точно, но напишу сюда.

2.)
1.  Конструкты которые выбрали роль, пока их оболочка находиться у вас в руке могут проходить сквозь стены а так же привязаны к вашей кукле и поворачиваются вместе с ней(как в старом баге когда рипли поднимал портал с человеком внутри)

2. Разорвать человека на шард на offering руне
    Сунуть шард в оболочку конструкта
    Взять оболочку в руки и дождаться пока человек выберет роль конструкта

3. оболочку конструкта нельзя взять в руки/ она будет выпадать из рук перед выбором роли игроком.

4 - 

3)
1. Повязка Зилота дает ночное зрение во всех последующих раундах если раунд закончиться пока она у вас на глазах

2. Надеть повязку и дождаться завершения раунда с ней на глазах
 
3. Бага не должно быть?

4. скрины сосут(я скриню только насри)

4)
1. Описание заклинания телепорт и заклинания выдающего снаряжение гласит что это заклинание превращает металл в рунический металл(или какая там хуйня у культа)

2. Подготовить заклинания на empowering руне
    Навести на них курсор для чтения описания 
3. (я очень понимаю что кодеры были в запаре и это простительно,просто пишу заранее что там должны стоять описания заклинаний)

4. Скрины у олега в подвале
5) 
1 За коим то хуем,при одном из вызовов Насри, руна Апокалипсиса вещала о том что Насри уже вызвана "You already summoned me" Как это произошло не совсем понятно

2. Попытаться стереть руну апокалипсиса во время вызова?
    Один из 10 культистов покинет руну во время вызова?
    Кто то сбросит вызов? 
    Кто то заспавнит Нар си?
3. Нарси приди

4. Вот тут очень печально что скрина нет

5.Вам вероятно об этом уже сообщал Nair sark так как он был педалью на момент бага которая пыталась что то пофиксить
 так же хотел бы сказать что перечерчение руны не помогает.
 
 
 Вроде все, если что докину еще завтра так как культ шанс у меня не слабый

**Comment by rhailrake** [comment]
разберусь

**Comment by Remuchi** [comment]
ура фиксим то, чему уже 2 месяца!
1 и 5 вроде как уже были пофикшены
2 пофикшено и будет залито в скором времени
3 и 4 взяты на заметку. Займусь ими в ближайшее время
