### ISSUE TITLE
[Feature] Сингуло слишком имбовая

### ISSUE THREAD

**Issue by SimobiSirOP** [frosty-dev/ss14-feedback#60]
- Описание идеи: Сделать ускоритель частиц, зависимым от Сингуляриума, нового топлива покупаемоего в КАРГО за 6к ящик с 30 штуками, потребление: 1 сингуляриум за 1 минуту активности. Причина реализации в том, чтобы сингулярность, имбовый источник энергии не был по типу "Сделал и забыл", таким образом заставляя инженеров следить за ней.

- Возможная реализация: Сингуляриум это два прототипа

- Дополнительные детали: Всё в описании

- Деньги: ЗА РАЗБАН ДЕНЬГИ, ЗА ФИЧУ ДЕНЬГИ, Я ТАК БОМЖЕМ СТАНУ

**Comment by Sevasstyan** [comment]
Если кому-то понравится может сделают. Но сейчас все заняты или фиксом багов, или допиливанием того, что у нас есть сейчас. Потому вряд-ли сделают... Им самим ничего не платят практически, а бесплатно не все готовы работать.
База короче

**Comment by SimobiSirOP** [comment]
> Если кому-то понравится может сделают. Но сейчас все заняты или фиксом багов, или допиливанием того, что у нас есть сейчас. Потому вряд-ли сделают... Им самим ничего не платят практически, а бесплатно не все готовы работать. База короче

Я сам же сделаю, если так пойдет, и одобрят идею

**Comment by Sevasstyan** [comment]
> > Если кому-то понравится может сделают. Но сейчас все заняты или фиксом багов, или допиливанием того, что у нас есть сейчас. Потому вряд-ли сделают... Им самим ничего не платят практически, а бесплатно не все готовы работать. База короче
> 
> Я сам же сделаю, если так пойдет, и одобрят идею

А, нихуя себе, понял. Мега харош, уважаю

**Comment by SimobiSirOP** [comment]
> > > Если кому-то понравится может сделают. Но сейчас все заняты или фиксом багов, или допиливанием того, что у нас есть сейчас. Потому вряд-ли сделают... Им самим ничего не платят практически, а бесплатно не все готовы работать. База короче
> > 
> > 
> > Я сам же сделаю, если так пойдет, и одобрят идею
> 
> А, нихуя себе, понял. Мега харош, уважаю

Сделаю, за анбан на основном дс сервере

**Comment by SimobiSirOP** [comment]
@ThereDrD0

**Comment by ThereDrD0** [comment]
> @ThereDrD0

Напиши грабле, если ему как гейдизу понравится фича и ты ее реализуешь, а он ее примет - я разбаню

**Comment by SimobiSirOP** [comment]
Закрыто, Грабли не отвечают
