### ISSUE TITLE
Атаки по себе.

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#84]
Предлагаю в качестве правки "баланса", либо "квалити оф лайф", добавить переключаемое действие, по типу харм мода, которое позволяло бы включать и отключать атаку по себе.

Из-за новой системы боя, многие перестали использовать ПКМ и стараются играть в основном через ЛКМ. Из-за того, что в сс14 все могут спокойно бегать через спрайты друг друга, часто возникают моменты, когда ты бьешь самого себя, пытаясь попасть в человека, который бежит прямо в тебя. 

А ситуации, когда ты действительно хочешь ударить именно по себе очень редки. Только когда тебя сильно порезали или подстрелили, ты можешь ебнуть по себе сваркой, в надежде что она тебя не убьет и остановит кровотечение. Но даже в таких ситуациях, многие просто лечатся наборами от ушибов, которые останавливают кровоток, либо закидываются таблетками с меда. 

То есть ситуаций, когда ты хочешь ударить себя буквально почти нету, а столкновения в ближнем бою повсеместны, и шанс случайно попасть по себе всегда присутствует, и он далеко не такой маленький, как можно подумать.
Я понимаю что добавлять миллион разных действий это как-то неправильно, но я считаю это лучшее решение. 
Либо можно сделать так, чтобы атаки по себе происходили только с зажатым альтом/шифтом.

(спасибо кстати что убрали промахи с ЛКМ, а то с ними вообще было тоскливо, прям.. очень...)

Денег, к сожалению, нет, но я надеюсь что кому-то из геймдизайнеров или кодеров зайдет данное решение, в качестве улучшения качества жизни. А также это немного повысит актуальность ближнего боя, который сейчас люто сосет. Конечно и раньше любой огнестрел был сильнее почти любого оружия ближнего боя, но сейчас это особенно чувствуется.

**Comment by ThereDrD0** [comment]
Это фича, в сс13 точно также ты можешь закликать сам себя. Ударить по себе станбатоном это критический провал твоих навыков робаста.

**Comment by Sevasstyan** [comment]
> Это фича, в сс13 точно также ты можешь закликать сам себя. Ударить по себе станбатоном это критический провал твоих навыков робаста.

Эх, понятно... Ну батоном я по себе пока ещё не попадал, но вот огнетушителем ножом или ящиком да.. 
Просто ну правда, в сс13 хотя бы нельзя свободно проходить друг через друга, там по себе чтобы попасть я даже не знаю кем нужно быть, ещё и движение потайловое. 
А в сс14 в тебя спокойно забегает челик, и может даже ударить по тебе находясь буквально в тебе.. А если ты чутка промажешь и заденешь свою модельку, в попытке попасть по такому челику, то сам себя уебешь.

Да я в целом согласен что все упирается в скилл ишуе, типо к любой херне можно привыкнуть, задрочить и использовать. Но мне кажется чисто для удобства было бы неплохо мою идею реализовать. 
Ну а там уже вам думать, надеюсь я дал кому-то так сказать пищу для размышления.

**Comment by rhailrake** [comment]
фича
