### ISSUE TITLE
СЛР от кота представили?

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-feedback#86]
Животные могут проводить слр

![image](https://github.com/frosty-dev/ss14-feedback/assets/88589686/c016786b-1088-49cf-8457-66affac82b67)

**Comment by Sevasstyan** [comment]
ПАХППААХАПХАППЗ, не ну а что, вдруг эти животные специально обученные? За 3 тысячи лет то, думаю животных могли и не таких вывести и обучить))
Ну а так,  реально рофельно, хехе

**Comment by rhailrake** [comment]
fixed
