### ISSUE TITLE
Некорректная работа ТТС с телекомами.

### ISSUE THREAD

**Issue by step1123** [frosty-dev/ss14-feedback#88]
Я заметил, что нововведённая фича телекомов с ТТС не совсем корректно работает с настройками ТТС.

Шаги для воспроизведения проблемы:
1. Встаньте рядом с телекомом.
2. В настройках выкрутите звуки ТТС на ноль.
3. Сделайте совершенно любое объявление по консоли связи, при том находясь рядом с телекомом.
4. Вы услышите то, как телеком озвучивает объявление, хотя вы отключили ТТС.

Я не должен слышать звуки ТТС Телекомов, если я отключил их в настройках ТТС.

**Comment by rhailrake** [comment]
@EnefFlow

**Comment by RavMorgan** [comment]
@step1123 Так и задумано.

**Comment by step1123** [comment]
Разве я должен слышать звуки ТТСа, если он отключен у меня в настройках?
