### ISSUE TITLE
[Feature] Телескопическая дубинка

### ISSUE THREAD

**Issue by Pantera5641** [frosty-dev/ss14-feedback#89]
- 1) Добавить телескопическую дубинку в игру. Работает как станбатон, только не требует батареек, но наносит меньше урона стамине.

- 2) Уже сделал 
       https://github.com/Pantera5641/Project.git

- 3) https://imgur.com/a/SqUb44S
![telebaton_on](https://github.com/frosty-dev/ss14-feedback/assets/144065128/a5730fe7-cefb-4091-817c-998fc17b8d2c)
![telebaton_off](https://github.com/frosty-dev/ss14-feedback/assets/144065128/32e377ab-27ea-4a04-a27d-80cd23ae9a9d)

- 4) Готов вложиться кодом

P.S. На видео с телебатоном есть вот эта синяя обводка, но по идее на билде white dream ее не должно быть, так как кажется, что она связана с компонентом стана.

**Comment by RavMorgan** [comment]
Здравствуйте, зачем вы притащили сюда кривой код Mr0maks'a, да еще и не указали его авторство?

**Comment by Valtosin** [comment]
Гений

**Comment by Pantera5641** [comment]
Ну ладно, кривой так кривой, проебался с кем не бывает

**Comment by Pantera5641** [comment]
Ну ладно, криво так криво, проебался с кем не бывает
