### ISSUE TITLE
[Feature] Добавить возможность подключить раздатчик реагентов к химмастеру

### ISSUE THREAD

**Issue by DEADISKO** [frosty-dev/ss14-feedback#9]
Я уже создавал тему в дискорде на канале заказов, но спустя месяц заказы были прикрыты.
Суть заказа такова: добавить возможность связать раздатчик реагентов и химмастер с помощью мультитула. Я конечно понимаю, что подключаемые устройства передают информацию, а не вещества или тому подобное, но, как я считаю, пытаться запариваться с какой-либо новой механикой по типу труб как в атмосии, которые передают жидкости было бы чересчур. 

Если игра сможет проверить, что устройства стоят на соседних тайлах не по диагонали, то при выполнении этого условия связать их. Это если вам нужно объяснение, как передаются жидкости из одного аппарата, то мы якобы подключаем короткие шланги. Но это опционально, чтобы избежать вопросов "как вещества появляются а химмастере".
После того, как устройства будут связанны у нас появится возможность заливать жидкость из раздатчика в химмастер напрямую. При нажатии по реагенту в раздатчике игра должна проверить, находится ли в нём мензурка. Если это так, то влить реагент в мензурку. В противном случае добавить реагент в буфер химмастера.
Другой полезной фишкой будет кнопка или тоглсвитч разрешающий реакцию в химмастере. 

Если вы играли на химике, то вы должны понимать, что после того, как вы заучили рецепты лекарств, геймплей превращается в унылое перекладывание мензурки из одного аппарата в другой. Я смотрел гайд на мед отдел, где ведущий притащил в свою комнату канистру воды и наделал таблеток с сахаром, чтобы не в покидать комнату при варке лекарств. Затем закрыл ставни, чтобы его не отвлекали другие люди своими просьбами. Повар не может приготовить фри без соли или салат без уксуса? Пусть станция питается сырыми продуктами. Нужно как все готовить одни гамбургеры. Туда же ботаников с их мутагенов, диэтиламином, робаст-гормоном. Туда же и уборщика с очистителем. Всё, химики играют в "преинтереснейший" кликер, не отвлекайте их!
А ещё на форуме обсуждали с одним человеком работу химика в теме, где он просил вернуть ёмкость таблетки в 50 единиц вещества. Мне было хорошо и с 20, вообще без разницы. Оказывается он любит экспериментировать смешивая лекарства. Я уже прошёл это и сама идея уже не интересовала меня так сильно. Я указал ему, что его лекарства пригодятся в случае 1 на 100 и это не стоит потраченных усилий и времени, за что я получил обвинение в том, что я просто скучный нуб, который ходит на работку в игре. Каждый остался при своём, но мы оба сошлись во мнении, что работа химика, я повторюсь, унылое перекладывание мензурки между аппаратами. 
Поэтому я и выдвинул такую идею. Облегчить нам обоим жизнь. Высвободить время для общения, экспериментов и других заказов.

Сумму, которую я готов внести - 2000 вечно падающей в пропасть валюты.

**Comment by Aviu00** [comment]
> Другой полезной фишкой будет кнопка или тоглсвитч разрешающий реакцию в химмастере

Слишком жирно. Можно будет так натыкать фтора и хлора в химмастер и разорвать все нажатием одной кнопки.

**Comment by DEADISKO** [comment]
Кстати, как и ожидалось - код не компилируется, а я пытался 😭

**Comment by DEADISKO** [comment]
> Можно будет так натыкать фтора и хлора в химмастер и разорвать все нажатием одной кнопки.

Хорошо, допустим, можно добавить кнопку "Смешать реагенты". Чтобы избежать создания взрыва путём смешивания фтора и хлора, а так же радиоактивного тумана из радия и так далее и тому подобное, мы добавим проверку на опасную смесь веществ в игру. Если такова будет - аппарат откажется смешивать реагенты. Я не программист, но я попытался что-то накидать:

```
static void IsMixtureBanned()
{
    bool containBannedMixture = false;
    string[] reagentsInBuffer = {};  // Допустим, этот массив отражает список реагентов, находящихся в буфере химмастера
    
    if (reagentsInBuffer.Contains("Chlorine") & reagentsInBuffer.Contains("Fluorine"))
    {
        containBannedMixture = true;
    }

    if (reagentsInBuffer.Contains("Water") & reagentsInBuffer.Contains("Potassium"))
    {
        containBannedMixture = true;
    }

    if (reagentsInBuffer.Contains("Phosphorus") & reagentsInBuffer.Contains("SulfuricAcid") & reagentsInBuffer.Contains("Plasma"))
    {
        containBannedMixture = true;
    }

    if (reagentsInBuffer.Contains("Phosphorus") & reagentsInBuffer.Contains("Potassium") & reagentsInBuffer.Contains("Sugar"))
    {
        containBannedMixture = true;
    }

    if (reagentsInBuffer.Contains("Fluorosurfactant") & reagentsInBuffer.Contains("Water"))
    {
        containBannedMixture = true;
    }

    if ((reagentsInBuffer.Contains("Iron") | reagentsInBuffer.Contains("Aluminium")) & reagentsInBuffer.Contains("FoamingAgent") & reagentsInBuffer.Contains("FluorosulfuricAcid"))
    {
        containBannedMixture = true;
    }

    return;
}
```

Затем при нажатии кнопки проверять значение переменной containBannedMixture и исходя из неё запускать реакцию или нет. Скажем, химмастер теперь смарт мэшин. И набегаторам труднее устроить пиздец.

**Comment by Aviu00** [comment]
> > Можно будет так натыкать фтора и хлора в химмастер и разорвать все нажатием одной кнопки.
> 
> Хорошо, допустим, можно добавить кнопку "Смешать реагенты". Чтобы избежать создания взрыва путём смешивания фтора и хлора, а так же радиоактивного тумана из радия и так далее и тому подобное, мы добавим проверку на опасную смесь веществ в игру. Если такова будет - аппарат откажется смешивать реагенты. Я не программист, но я попытался что-то накидать:
> 
> Затем при нажатии кнопки проверять значение переменной containBannedMixture и исходя из неё запускать реакцию или нет. Скажем, химмастер теперь смарт мэшин. И набегаторам труднее устроить пиздец.

Ну, как по мне метод этот слишком костыльный, это во первых. Во вторых, смешивание реагентов в химмастере полностью убирает смысл в мензурках, то есть не важно, какая емкость в мензурке, ибо мы ее вообще не используем. Первая фича и так жизнь облегчит достаточно. Ну и сейчас и так можно смешивать вещества сразу в таблетках при создании. Как по мне, луше просто добавить в химмастер кнопки перемещения веществ, скажем по 15, 20, 30, 75, чтобы было удобнее в мензурках смешивать.

**Comment by DEADISKO** [comment]
> Смешивание реагентов в химмастере полностью убирает смысл в мензурках, то есть не важно, какая емкость в мензурке, ибо мы ее вообще не используем. Ну и сейчас и так можно смешивать вещества сразу в таблетках при создании.

Ну, смешивание в таблетках при создании мне не очень нравится, так как получаются примеси или типа того. Например, смешивает не не 25 единиц вещества, а 24.99 и ещё 0.01 остаточного ингредиента.

По поводу мензурок - хз. Они ещё нужны для нагревания веществ и производства того же мета. Или для измельчения таблеток в измельчителе.

По моему мнению, работа химиков очень проста с точки зрения механик, но очень занудна. Если бы не бы

**Comment by DEADISKO** [comment]
> Ну, как по мне метод этот слишком костыльный, это во первых. Во вторых, смешивание реагентов в химмастере полностью убирает смысл в мензурках, то есть не важно, какая емкость в мензурке, ибо мы ее вообще не используем. Первая фича и так жизнь облегчит достаточно. Ну и сейчас и так можно смешивать вещества сразу в таблетках при создании. Как по мне, лучше просто добавить в химмастер кнопки перемещения веществ, скажем по 15, 20, 30, 75, чтобы было удобнее в мензурках смешивать.

Мне не нравится идея смешивания лекарств в таблетках из-за нерациональных чисел, которые получаются в некоторых случаях. По итогу состав таблетки получается как условные 24,99 лекарства и 0,01 одного из ингредиентов.

Мензурки ещё требуются для нагревания смесей на электроплитке и измельчения таблеток или растений в измельчителе. Ну или для разливания лекарств в бутылочки. Хотя я бы предпочёл чтобы можно было бы загрузить кучу бутылочек в тот же химмастер и чтобы он штамповал их на конвейер.

По поводу костыля я согласен - идея не очень. В принципе добавить кнопок не помешало бы.
Ну или стандартную неотъёмную ёмкость в химмастере на 300 единиц, но как её реализовать я не знаю.

Моё мнение о работе химика это то, что работа слишком простая (нажимай кнопки да перекладывай мензурки), но очень муторная. Углубить её для игры, где сессия длится около часа непереусложнив будет сложно. У меня есть пару мыслей, может в будущем я их продумаю и предложу.

**Comment by Aviu00** [comment]
@DEADISKO напиши в дискорде мне, я aviu00
