### ISSUE TITLE
Скорость движения во время получения стаминурона

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#91]
Возможно это именно фича, но я не уверен и хочу убедится, потому напишу.

Когда ты наносишь урон по стамине человеку любим способом, будь то диззейблер или боксерские перчатки, и стамина падает ниже половины от своего показателя, человек сильно замедляется. Однако, замедление это временное, и после около 2-3 секунд, человек возвращает свою изначальную скорость, при этом имея стамины ниже половины.
И даже если продолжать наносить урон по стамине, но не доводить его до нуля, например боксерскими перчатками, все равно скорость восстановится и замедление пройдет, даже если стамины уже практически нету. 
Так и должно работать?

Вообще очень неплохая фича, если челик проебался и не смог по тебе попасть дубиной или диззом еще раз во время этого короткого промежутка сильного замедления, то у тебя есть шанс убить его или убежать. Тем более что нелетал очень силен, в некоторых ситуациях сильнее летала, и такая механика просто дает шанс на спасение от нелетала. 
Но так как я не уверен, хочу просто убедится в том, что это фича.

**Comment by rhailrake** [comment]
фича
