### ISSUE TITLE
Способность телепорта просто так уходит на кд

### ISSUE THREAD

**Issue by Sevasstyan** [frosty-dev/ss14-feedback#94]
Я не ебу в чем дело, но периодически способность телепорта взятая с руны сама по себе уходит на кулдаун, и это порой ПИЗДЕЦ как руинит игры. 

Я не знаю, вот логи что-ли, если чем-то помогут.

[client.stdout.log](https://github.com/frosty-dev/ss14-feedback/files/12563853/client.stdout.log)

**Comment by rhailrake** [comment]
@Sevasstyan запишите видео пожалуйста, клиент логи мне ничего не дадут.

**Comment by Sevasstyan** [comment]
> @Sevasstyan запишите видео пожалуйста, клиент логи мне ничего не дадут.

Понял, если мне наконец-то снова выпадет культ попробую заснять

**Comment by Sevasstyan** [comment]
> @Sevasstyan запишите видео пожалуйста, клиент логи мне ничего не дадут.

@rhailrake Я записал видос, но сюда залить не могу. Лучше в дсе скинуть тебе в лс, или на гугл диск загружать и ссылку сюда кидать?

**Comment by RavMorgan** [comment]
> > @Sevasstyan запишите видео пожалуйста, клиент логи мне ничего не дадут.
> 
> @rhailrake Я записал видос, но сюда залить не могу. Лучше в дсе скинуть тебе в лс, или на гугл диск загружать и ссылку сюда кидать?

Как хочешь

**Comment by Sevasstyan** [comment]
Короче

https://drive.google.com/file/d/1SXxhMw2X-cQ115PSWI2Q_OCJ1q-irxNS/view?usp=sharing

Вот первая ссылка. Здесь видно как способности, и не только телепорт кстати, просто сами по себе уходят на кд. А потом кстати способность вызова снаряжения вдруг перестала откатываться и замерла на месте, потом понемногу оно откатывалось, но ОЧЕНЬ долго.

https://drive.google.com/file/d/1PKCPv6RnLziQGhFCtYMfHJ14EVj6RtHb/view?usp=sharing

Ну  вторая ссылка, там тоже видно.

**Comment by Sevasstyan** [comment]
> @Sevasstyan запишите видео пожалуйста, клиент логи мне ничего не дадут.

Короче

https://drive.google.com/file/d/1SXxhMw2X-cQ115PSWI2Q_OCJ1q-irxNS/view?usp=sharing

Вот первая ссылка. Здесь видно как способности, и не только телепорт кстати, просто сами по себе уходят на кд. А потом кстати способность вызова снаряжения вдруг перестала откатываться и замерла на месте, потом понемногу оно откатывалось, но ОЧЕНЬ долго. В итоге я умер быстрее чем оно успело откатиться, видос я обрезал на моменте смерти практически.

https://drive.google.com/file/d/1PKCPv6RnLziQGhFCtYMfHJ14EVj6RtHb/view?usp=sharing

Ну  и вторая ссылка, там такая же херня. Кстати вначале видно еще одну проблему, скиллы тупо блять не брались, по миллиону раз тыкаешь, и через хуй знает сколько оно берется. Такая же хуйня с крафтом. Дико бесячая, но не основная проблема. 

Если видосы хуйня, я могу скинуть полные версии записи.

**Comment by Aviu00** [comment]
Вроде как это пофиксили.

**Comment by Sevasstyan** [comment]
ДА, ЭТО СЛАВА БОГУ ПОФИКСИЛИ! Спасибо!
