### ISSUE TITLE
Real name, вместо fake

### ISSUE THREAD

**Issue by PuroSlavKing** [frosty-dev/ss14-feedback#95]
**Описание ошибки**
Пезда, при осмотре персонажа с чужой id картой, и закрытым лицом, показывается настоящее имя!!! Это ахуй!!!

**Для воспроизведения ошибки**
Шаги для воспроизведения проблемы:
1. Спиздите чужую ID
2. Закройте свой еблет противогазом
3. Вставьте чужую ID в слот карты
4. Осмотрите себя

**Скриншоты/логи**
Обязательно добавьте скриншоты/логи ошибки, если они конечно же есть.
![image](https://github.com/frosty-dev/ss14-feedback/assets/103608145/4151d015-b759-42cf-a268-a210a77a0edc)

**Comment by RavMorgan** [comment]
@rhailrake
