### ISSUE TITLE
Голые арахниды!!!

### ISSUE THREAD

**Issue by PuroSlavKing** [frosty-dev/ss14-feedback#96]
**Описание ошибки**
У арахнидов нету трусиков и бра!!!

**Для воспроизведения ошибки**
Шаги для воспроизведения проблемы:
1. Стать арахнидом
2. Посмотреть на свою промежность
3. Убедиться, что вы не видите трусов

**Скриншоты/логи**
Обязательно добавьте скриншоты/логи ошибки, если они конечно же есть.
![image](https://github.com/frosty-dev/ss14-feedback/assets/103608145/2c2d8f9a-6856-4827-a9b2-48c01d68ac67)
![image](https://github.com/frosty-dev/ss14-feedback/assets/103608145/df70615e-824d-46e6-8662-6d826d94f760)

**Comment by Pantera5641** [comment]
Не баг, а фича.
